### ISSUE TITLE
soReusePort socket option fails on windows

### ISSUE THREAD

**Issue by ondrejhavelka** [avast/scala-server-toolkit#764]
## Describe the bug
On Windows, the blaze server wants to set the `SO_REUSEPORT` socket options which is not available and it fails when the server accepts a request and sets the sockets options on sun.nio.ch.SocketChannelImpl#setOption

The bug was introduced within https://github.com/avast/scala-server-toolkit/pull/607

## To Reproduce
Run the server on any windows machine and make a request

## Additional context
```2021-12-15 09:40:28.041 ERROR [          ] [  blaze-acceptor-0-0]  o.http4s.blaze.channel.nio1.NIO1SocketServerGroup: Error handling client channel. Closing.
java.lang.UnsupportedOperationException: 'SO_REUSEPORT' not supported
	at java.base/sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:215)
	at org.http4s.blaze.channel.nio1.NIO1ClientChannel.$anonfun$configureOptions$1(NIO1ClientChannel.scala:48)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at org.http4s.blaze.channel.nio1.NIO1ClientChannel.configureOptions(NIO1ClientChannel.scala:47)
	at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.org$http4s$blaze$channel$nio1$NIO1SocketServerGroup$$handleClientChannel(NIO1SocketServerGroup.scala:302)
	at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$SocketAcceptor.acceptNewConnections(NIO1SocketServerGroup.scala:181)
	at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$SocketAcceptor.opsReady(NIO1SocketServerGroup.scala:150)
	at org.http4s.blaze.channel.nio1.SelectorLoop.processKeys(SelectorLoop.scala:195)
	at org.http4s.blaze.channel.nio1.SelectorLoop.org$http4s$blaze$channel$nio1$SelectorLoop$$runLoop(SelectorLoop.scala:165)
	at org.http4s.blaze.channel.nio1.SelectorLoop$$anon$1.run(SelectorLoop.scala:59)
	at java.base/java.lang.Thread.run(Thread.java:829)```

**Comment by jakubjanecek** [comment]
Hi. You can set the option to `false` and that should resolve your problem. Is that ok?

**Comment by ondrejhavelka** [comment]
unfortunately no,
the problem is the missing feature on Windows and it fails regardless of the value
it tries to set the option that is not available on Windows 

we discuss it with @sideeffffect on slack and it a bug in SST

I also tried the example application and it also fails

**Comment by ondrejhavelka** [comment]
from debugging 
![image](https://user-images.githubusercontent.com/21736302/146192723-392c7f3f-1644-4f00-88e9-684bb34f0e06.png)
